added some git related functions; safer rm; alias to edit aliases; display rvm version in zsh prompt

diff --git a/zsh/functions b/zsh/functions
--- a/zsh/functions
+++ b/zsh/functions
@@ -1,3 +1,27 @@
+function gbt() {
+  git branch --track $2 $1/$2
+  git checkout $2
+}
+
+function grf() {
+  rm $1
+  git checkout $1
+}
+
+function detect_rvm_version {
+  local gemset=$(echo $GEM_HOME | awk -F'@' '{print $2}')
+  [ "$gemset" != "" ] && gemset="@$gemset"
+  local version=$(echo $MY_RUBY_HOME | awk -F'-' '{print $2}')
+  [ "$version" != "" ] && version="$version"
+  local full="$version$gemset"
+  [ "$full" != "" ] && echo "$full"
+}
+
+# Creating a remote tracking branch
+function track { 
+  git branch --track $1 "origin/$1"
+}
+
 function git-new-remote-tracking {
   git checkout -b $1 && git push -u origin $1
 }
@@ -45,3 +69,42 @@ function take {
 function gc {
   git commit -m "$*"
 }
+
+
+function rmf(){
+   for file in $*
+   do
+      __rm_single_file $file
+   done
+}
+
+function __rm_single_file(){
+       if ! [ -d ~/.Trash/ ]
+       then
+               command /bin/mkdir ~/.Trash
+       fi
+
+       if ! [ $# -eq 1 ]
+       then
+               echo "__rm_single_file: 1 argument required but $# passed."
+               exit
+       fi
+
+       if [ -e $1 ]
+       then
+               BASENAME=`basename $1`
+               NAME=$BASENAME
+               COUNT=0
+               while [ -e ~/.Trash/$NAME ]
+               do
+                       COUNT=$(($COUNT+1))
+                       NAME="$BASENAME.$COUNT"
+               done
+
+               command /bin/mv $1 ~/.Trash/$NAME
+       else
+               echo "No such file or directory: $file"
+       fi
+}
+
+#alias rm='rmf'
